http:
  middlewares:

    middlewares-basic-auth:                                           # Ejemplo de autentificaci칩n b치sica
      basicAuth:
        usersFile: "/ruta/archivo/seguro/.usuarios"                   # Asegurarse de montar el volumen en docker-compose.yml

    middlewares-rate-limit:
      rateLimit:
        average: 100
        burst: 50

    middlewares-authelia:                                             # Bloquea el acceso mediante autentificaci칩n con Authelia (ver en authelia)
      forwardAuth:
        address: http://authelia:9091/api/authz/forward-auth

    middlewares-crowdsec-bouncer:                                     # Componente del sistema Crowdsec que toma las acciones (ver en crowdsec)
      forwardAuth:
        address: http://bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true

    middlewares-secure-headers:                                       # Encabezados de seguridad de uso general
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        # forceSTSHeader: true
        customFrameOptionsValue: "allow-from https:ejemplo.com"       # Ajustar el dominio.
        contentTypeNosniff: true
        browserXssFilter: true
        # sslForceHost: true                                          # A침ade sslHost a todos los servicios
        # sslHost: "ejemplo.com"
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,noindex,nofollow,"
          server: ""

    nextcloud-secure-headers:                                         # Los mismos encabezados de seguridad anteriores, pero cambiando X-Robots-Tag (requerido por Nextcloud)
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        # forceSTSHeader: true
        customFrameOptionsValue: "allow-from https:ejemplo.com"       # Ajustar el dominio.
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        customResponseHeaders:
          X-Robots-Tag: "noindex,nofollow"
          X-Frame-Options: "sameorigin"
          server: ""

    nextcloud-redirect:                                               # Reescribe las peticiones CardDAV y CalDAV para su uso en clientes externos
      redirectRegex:                                                  # Ver: https://docs.nextcloud.com/server/14/admin_manual/issues/general_troubleshooting.html#service-discovery
        permanent: true
        regex: "https://(.*)/.well-known/(card|cal)dav"
        replacement: "https://${1}/remote.php/dav/"

